/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#ifndef __PLUGINEDITOR_H_3122DB61__
#define __PLUGINEDITOR_H_3122DB61__

#include "../JuceLibraryCode/JuceHeader.h"
#include "PluginProcessor.h"


//==============================================================================
/**
*/
class StompBoxAudioProcessorEditor  : public AudioProcessorEditor
{
public:
    StompBoxAudioProcessorEditor (StompBoxAudioProcessor* ownerFilter);
    ~StompBoxAudioProcessorEditor();

    //==============================================================================
    // This is just a standard Juce paint method...
    void paint (Graphics& g);
private:
    ScopedPointer<Component> panel;
};


#endif  // __PLUGINEDITOR_H_3122DB61__
